// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// CindexCR_cpp
double CindexCR_cpp(const arma::vec& time, const arma::vec& status, const arma::vec& predicted, const int Cause_int);
RcppExport SEXP _CompRiskRE_CindexCR_cpp(SEXP timeSEXP, SEXP statusSEXP, SEXP predictedSEXP, SEXP Cause_intSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type time(timeSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type status(statusSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type predicted(predictedSEXP);
    Rcpp::traits::input_parameter< const int >::type Cause_int(Cause_intSEXP);
    rcpp_result_gen = Rcpp::wrap(CindexCR_cpp(time, status, predicted, Cause_int));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_CompRiskRE_CindexCR_cpp", (DL_FUNC) &_CompRiskRE_CindexCR_cpp, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_CompRiskRE(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
