# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

CindexCR_cpp <- function(time, status, predicted, Cause_int) {
    .Call(`_CompRiskRE_CindexCR_cpp`, time, status, predicted, Cause_int)
}

